CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashedPassword VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    profilePicture VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservations(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    reservationDate DATE NOT NULL,
    reservationTime TIME NOT NULL,
    reservationService VARCHAR(50),
    pet VARCHAR(255),
    allergies CLOB,
    suggestions CLOB,
    CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);